### ISSUE TITLE
Need XCode version 16

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [cedvdb/action-flutter-build-ios#11]
how to make the build proccess runs on xcode 16 instead if the default Xcode 15.4 that shows in the workflow log

Github log

```
Run cedvdb/action-flutter-build-ios@v1
Run /usr/bin/xcodebuild -version
Xcode 15.4
```

Workflow file
```yaml
jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --flavor staging --dart-define=ENV=staging --export-options-plist=ios/config/staging/ExportOptions.plist
          certificate-base64: ${{ secrets.IOS_CERTIFICATE }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_STAGING_THABAT }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

```

**Comment by AlaaEldeenYsr** [comment]
After multiple tries I managed to handle it through below script.

```
- name: Set up Xcode 16
  uses: maxim-lobanov/setup-xcode@v1
  with:
    xcode-version: "16"
```
